site_name: flowMC
site_description: Normalizing-flow enhanced sampling package for probabilistic inference in Jax
site_author: Kaze Wong
repo_url: https://github.com/kazewong/flowMC
repo_name: kazewong/kazewong

theme:
    name: material
    features:
        - navigation  # Sections are included in the navigation on the left.
        - toc  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: cyan
          accent: deep purple
          toggle:
             icon: material/brightness-5
             name: Dark mode
        - scheme: slate
          primary: custom
          accent: purple
          toggle:
             icon: material/brightness-2
             name: Light mode

    twitter_name: "@physicskaze"
    twitter_url: "https://twitter.com/physicskaze"

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "Â¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mkdocs-jupyter: # Jupyter notebook support
        # show_input: False
    - gen-files:
        scripts:
        - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()
                    - import jaxtyping
                    - jaxtyping.set_array_name_format("array")

                optional:
                    docstring_style: google
                    inherited_members: true  # Allow looking up inherited methods
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4


extra_css:
  - stylesheets/extra.css

nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - Tutorial:
        - Step-by-step guide: tutorials/dualmoon.ipynb
        - Custom Strategy: tutorials/custom_strategy.ipynb
        - Training Normalizing Flow: tutorials/train_normalizing_flow.ipynb
        - Loading Resource: tutorials/loading_resources.ipynb
    - Community Examples: communityExamples.md
    - FAQ: FAQ.md
    - Contribution: contribution.md
    - API: api/flowMC/*
